name: gym-duckietown
channels:
    - defaults
dependencies:
    - python=3.9
    - pyzmq
    - numpy
    - pyyaml
    - pip:
        - gym
        - pyglet
        - opencv-python
        - scikit-image
        - dataclasses
        - pygeometry
